import { ProductItem } from "./app/shared/models/ProductItem";
import { Tag } from "./app/shared/models/Tag";
import { News } from "./app/shared/models/News";
export const sampleProductItems: ProductItem[] = [
  {
    id: '1',
    name: 'Champagne Dom Perignon Vintage 2008',
    originalPrice: 13000000,
    price: 10000000,
    stars: 4.5,
    imageUrl: 'assets/vine.jpg',
    tags: ['Vine'],
    unitCapitity: 12.6,
    unitPrice: 2.97,
    Upc: '0026033748472',
    Descriptions: 'Brisket',
    address: 'Located in Aisle 1',
    promotions: '2 deals available',
    added: false,
    addedSugar: false,
    productQuantityAddDefault: 1,
  },
  {
    id: '2',
    name: '14 Hands Winery Selfpoint',
    originalPrice: 3000000,
    price: 2000000,
    stars: 4.7,
    imageUrl: 'assets/vine2.jpg',
    tags: ['Vine'],
    unitCapitity: 14.5,
    unitPrice: 2.55,
    Upc: '0026033564321',
    Descriptions: 'Brisket',
    address: 'Located in Aisle 2',
    promotions: '2 deals available',
    added: false,
    addedSugar: false,
    productQuantityAddDefault: 1,
  },
  {
    id: '3',
    name: 'Beer Corona Extra',
    originalPrice: 40000,
    price: 35000,
    stars: 3.5,
    imageUrl: 'assets/beer1.jpg',
    tags: ['Beer'],
    unitCapitity: 12.5,
    unitPrice: 2.32,
    Upc: '0026033123321',
    Descriptions: 'Brisket',
    address: 'Located in Aisle 3',
    promotions: '2 deals available',
    added: false,
    addedSugar: false,
    productQuantityAddDefault: 1,
  },
  {
    id: '4',
    name: 'Chimay Doree Gold',
    originalPrice: 40000,
    price: 30000,
    stars: 3.3,
    imageUrl: 'assets/beer2.jpg',
    tags: ['Beer'],
    unitCapitity: 10.5,
    unitPrice: 2.10,
    Upc: '0026033456789',
    Descriptions: 'Brisket',
    address: 'Located in Aisle 4',
    promotions: '2 deals available',
    added: false,
    addedSugar: false,
    productQuantityAddDefault: 1,
  },
  {
    id: '5',
    name: 'Mad River Distillers Bourbon',
    originalPrice: 4000000,
    price: 1000000,
    stars: 3.0,
    imageUrl: 'assets/spri1.jpg',
    tags: ['Whiskey'],
    unitCapitity: 11.5,
    unitPrice: 2.11,
    Upc: '0026033159753',
    Descriptions: 'Brisket',
    address: 'Located in Aisle 5',
    promotions: '2 deals available',
    added: false,
    addedSugar: false,
    productQuantityAddDefault: 1,
  },
  {
    id: '6',
    name: 'Lyres Dry London Spirit',
    originalPrice: 6000000,
    price: 3000000,
    stars: 3.0,
    imageUrl: 'assets/spri2.jpg',
    tags: ['whiskey'],
    unitCapitity: 14.3,
    unitPrice: 2.33,
    Upc: '0026033456852',
    Descriptions: 'Brisket',
    address: 'Located in Aisle 6',
    promotions: '2 deals available',
    added: false,
    addedSugar: false,
    productQuantityAddDefault: 1,
  },
  {
    id: '7',
    name: 'GIN BOMBAY SAPPHIRE',
    originalPrice: 1000000,
    price: 500000,
    stars: 3.0,
    imageUrl: 'assets/bombay.jpg',
    tags: ['Spririts & Liqueur'],
    unitCapitity: 12.3,
    unitPrice: 2.14,
    Upc: '0026033482159',
    Descriptions: 'Brisket',
    address: 'Located in Aisle 7',
    promotions: '2 deals available',
    added: false,
    addedSugar: false,
    productQuantityAddDefault: 1,
  },
  {
    id: '8',
    name: 'VODKA DANZKA',
    originalPrice: 300000,
    price: 155000,
    stars: 3.0,
    imageUrl: 'assets/danzka.jpg',
    tags: ['Spririts & Liqueur'],
    unitCapitity: 13.1,
    unitPrice: 2.28,
    Upc: '0026033197536',
    Descriptions: 'Brisket',
    address: 'Located in Aisle 8',
    promotions: '2 deals available',
    added: false,
    addedSugar: false,
    productQuantityAddDefault: 1,
  },
]

export const sample_tags: Tag[] = [
  // {name:'All', count:6, imageUrlTag: 'assets/vine2.jpg'},
  { name: 'Vine', count: 2, imageUrlTag: 'assets/spri2.jpg' },
  { name: 'Beer', count: 1, imageUrlTag: 'assets/beer1.jpg' },
  { name: 'Whiskey', count: 4, imageUrlTag: 'assets/spri1.jpg' },
  { name: 'Spririts & Liqueur', count: 2, imageUrlTag: 'assets/bombay.jpg' },
]

export const sample_news: News[] = [
  {
    imageUrlnew: 'assets/blog1.webp',
    title: 'Vinography Unboxed: Week of 11/26/23',
    content: 'This past week included a few wines that didn’t make the final cut for inclusion in my roundup of the best sparkling wines in California that I wrote for Jancis Robinson last month.',
    date: '11/26/23',
    url: 'https://www.vinography.com/2023/12/vinography-unboxed-week-of-11-26-23',
  },

  {
    imageUrlnew: 'assets/blog2.webp',
    title: 'The 2023 Vinography Holiday Gift Guide for Wine Lovers',
    content: 'There are always two things noticeably absent from this guide, and very much on purpose.',
    date: '17-11-2023',
    url: 'https://www.vinography.com/2023/11/the-2023-vinography-holiday-gift-guide-for-wine-lovers',
  },

  {
    imageUrlnew: 'assets/blog3.webp',
    title: 'California’s Top Sparkling Wines',
    content: 'We’ve seen a refocus in California sparkling wine to site specificity, with people making wines that are much more targeted in their terroir expression',
    date: '17-11-2023',
    url: 'https://www.vinography.com/2023/11/californias-top-sparkling-wines',

  },
  {
    imageUrlnew: 'assets/blog4.webp',
    title: 'The World’s Greatest Wine Reference Book Gets a Major Overhaul',
    content: 'For the first time, the editorship of this book was handed off to Julia Harding and her new partner in crime Tara Q.',
    date: '31-10-2023',
    url: 'https://www.vinography.com/2023/10/the-worlds-greatest-wine-reference-book-gets-a-major-overhaul',
  },

]